# Generated by Django 3.0.4 on 2020-03-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200309_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Pacient', max_length=255),
        ),
    ]
