# Generated by Django 3.0.4 on 2020-03-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_auto_20200330_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='medicaments',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='payment',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='symtoms',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='treatment',
            field=models.CharField(max_length=255),
        ),
    ]
