# Generated by Django 3.0.4 on 2020-03-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_auto_20200331_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='medicaments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='payment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='symtoms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='treatment',
            field=models.TextField(),
        ),
    ]
