# Generated by Django 3.0.4 on 2020-04-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_auto_20200331_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='medicaments',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='payment',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='symtoms',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='treatment',
            field=models.CharField(max_length=255),
        ),
    ]
