# Generated by Django 3.0.4 on 2020-04-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_auto_20200401_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultations',
        ),
    ]
