# Generated by Django 3.0.4 on 2020-03-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20200317_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='block_id',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='user_id',
            new_name='user',
        ),
    ]
