# Generated by Django 3.0.4 on 2020-04-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_consultations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultations',
            old_name='pacient',
            new_name='user',
        ),
    ]
