# Generated by Django 3.0.4 on 2020-04-01 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20200401_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.WorkBlocks'),
        ),
    ]
