# Generated by Django 3.0.4 on 2020-04-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_auto_20200403_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='medicaments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='symtoms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='treatment',
            field=models.TextField(),
        ),
    ]
